# The Use of Matrices in Computer Graphics
### By Shahzeb Khan
### For Professor Philley's Linear Algebra class.

In [1]:
import numpy as np

In [11]:
a = np.matrix('7 3 10')
b = np.matrix('1 4; 2 9; 3 8')
print('Matrix a is:')
print(a)
print('Matrix b is:')
print(b)
c = a * b
print('C is:')
print(c)

Matrix a is:
[[ 7  3 10]]
Matrix b is:
[[1 4]
 [2 9]
 [3 8]]
C is:
[[ 43 135]]
